import Head from 'next/head'
import Specialties from '../components/home/specialties';
import SocialNetworkBoxes from '../components/home/socialNetworkBoxes';

export default function Home() {
  
  const dataExpertises = [
    {
      imageCategory: './images/home/terminal.png',
      title: 'Expertises',
      images: ['./images/home/languages/js.png', './images/home/languages/ts.png', './images/home/languages/nodejs.png', './images/home/languages/html.png', './images/home/languages/css.png' ],
      titleImage:['Javascript', 'TypeScript', 'NodeJS', 'HTML', 'CSS']
    },
    {
      imageCategory: './images/home/box.png',
      title: 'Frameworks',
      images: ['./images/home/frameworks/nextjs.png', './images/home/frameworks/react.png', './images/home/frameworks/jquery.png', './images/home/frameworks/scss.png', './images/home/frameworks/redax.png', './images/home/frameworks/mui.png', './images/home/frameworks/bootstrap.png', './images/home/frameworks/tailwind.png', './images/home/frameworks/regex.png', './images/home/frameworks/wordpress.png' ],
      titleImage:['NextJS', 'ReactJS', 'jQuery', 'Sass', 'Redux', 'MUI', 'Bootstrap', 'Tailwind', 'Regex', 'WordPress']
    },
    {
      imageCategory: './images/home/git-pull-request.png',
      title: 'Tools',
      images: ['./images/home/tools/figma.png', './images/home/tools/git.png', './images/home/tools/linux.png', './images/home/tools/vscode.png'],
      titleImage:['Figma', 'Git', 'VScode', 'Linux']
    },
  ]

  return (
    <>
    <Head>
      <title>Home - DevPCT</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="./favicon.ico" />
    </Head>


    <header >
      <div className="flex w-full lg:justify-center  lg:flex-row flex-col gap-x-[4rem] gap-y-[3rem] lg:text-justify text-center">
        <div className='text-center rounded-b-[100%] lg:m-0 m-auto overflow-hidden w-[15rem] h-[16rem]  bg-[#EDB836] pt-[1rem] '>  
          <img className='w-full h-full' src="https://avatars.githubusercontent.com/u/102470936?v=4" loading='lazy'/>
        </div>
        <div className='lg:mt-[3.5rem] w-[70%] lg:m-0 m-auto'>
          <h2 className='text-[1.9rem] font-[300]'>Mohammad</h2>
          <h1 className='text-[2.5rem]'>Abdollahzadeh</h1>
          <hr className='mt-[1rem] mb-[0.4rem] w-full border-[#EDB836] border-[2px] rounded-full' />
          <p className='md:text-[1.2rem] text-[1rem] font-bold ml-[1rem] tracking-[0.2rem]'>FRONTEND DEVELOPER</p>
        </div>
      </div>
        <img className='md:mt-[7rem] lg:mt-0 w-full md:h-[35vh] h-[15vh]  absolute lg:top-[10rem] md:top-[14rem]' src="./images/home/line.png" loading='lazy' />
    </header>


    <main className='md:mt-[17rem] mt-[10rem]'>
      <div className='flex items-center w-full gap-x-[1rem] justify-center '>
      <img className='w-[3rem] h-[3rem]' src="./images/home/expertises.png" loading='lazy'/>
      <p className='text-[3rem] font-medium'>Expertises</p>
      </div>

      <div className='w-full h-fit lg:pl-[10rem] px-[2rem] mt-[5rem]'>

      {dataExpertises.map((item, index) => (
        <Specialties
          key={index}
          imageCategory={item.imageCategory}
          title={item.title}
          images={item.images}
          titleImage={item.titleImage}
        />
      ))}
 
      </div>
    </main>


    <footer className='w-full'>
        <div className='w-full h-full bg-[#D9D9D9] md:p-[2.5rem] p-[1rem] rounded-t-[52px] md:mt-[9rem]'>
          
          <div className='flex items-center justify-center gap-x-5'>
            <img className='w-[3rem]' src="./images/home/message.png" loading='lazy' />
            <p className='lg:text-[2.2rem] text-[2rem] font-medium'>Connect with me</p>
          </div>

        <SocialNetworkBoxes/>

        </div>
    </footer> 
    </>
  )
}